const cartTypes = {
    ADD_TO_CART_PRODUCT : "ADD_TO_CART_PRODUCT",
    ADD_TO_CART : "ADD_TO_CART",
    REMOVE_FROM_CART:"REMOVE_FROM_CART",
     CHECKOUT_REQUEST:  'CHECKOUT_REQUEST',
 CHECKOUT_SUCCESS  :'CHECKOUT_SUCCESS',
 CHECKOUT_FAILURE  :'CHECKOUT_FAILURE'
}

export default cartTypes